### PR TITLE
Update class 2

### PR DESCRIPTION
**Pull request by chadni00**

### CODE REVIEW

**Comment by tajnur007** [comment]
Hello @chadni00,
In this PR, there haven't any changes. Would you please check this PR?

**Comment by chadni00** [comment]
bhaiya I didn't understand what you said in your comment

**Comment by chadni00** [comment]
@tajnur007 bhaiya I didn't understand what you said in your comment

**Comment by tajnur007** [comment]
image

The marked section indicates that there have no file changes. So you can merge. Approved!

**Review by tajnur007 — APPROVED** [review]

**Pull request closed without merging**
